package visao;

import controle.ControleDocente;
import java.time.LocalDate;

public class TelaCadastroDocente extends javax.swing.JFrame {

    private String nome;
    private String cpf;
    private String email;
    private String genero;
    private String formacao;
    private LocalDate dataNascimento;
    private ControleDocente controleDocente;
    private boolean editar;

    public TelaCadastroDocente(ControleDocente controleDocente) {
        initComponents();
        this.controleDocente = controleDocente;
        /*buttonGroup1.add(jRB_Masculino);
        buttonGroup1.add(jRB_Feminino);
        buttonGroup1.clearSelection();*/
        setLocationRelativeTo(null);
    }

    public TelaCadastroDocente(ControleDocente controleDocente, ListaDocentes telaListaDocentes, String nome, String cpf, String email, String formacao, String genero, LocalDate dataNascimento) {
        this(controleDocente);
        this.nome = nome;
        this.cpf = cpf;
        this.email = email;
        this.genero = genero;
        this.formacao = formacao;
        this.dataNascimento = dataNascimento;
        editar = true;
        setarDadosTela();
    }

    private void setarDadosTela() {
        jTF_Nome.setText(nome);
        jTF_Cpf.setText(cpf);
        jTF_Email.setText(email);

        if (this.genero.equalsIgnoreCase("Masculino")) {
            jRB_Masculino.setSelected(true);
        } else if (this.genero.equalsIgnoreCase("Feminino")) {
            jRB_Feminino.setSelected(true);
        }

        if (dataNascimento != null) {
            jS_Dia.setValue(dataNascimento.getDayOfMonth());
            jS_Mes.setValue(dataNascimento.getMonthValue());
            jS_Ano.setValue(dataNascimento.getYear());
        }
        jCB_Curso.setSelectedItem(formacao);
//        jCB_Curso.setSelectedIndex(2);
    }

    public String getNome() {
        return nome;
    }

    public String getCpf() {
        return cpf;
    }

    public String getEmail() {
        return email;
    }

    public String getGenero() {
        return genero;
    }

    public String getFormacao() {
        return formacao;
    }

    public LocalDate getDataNascimento() {
        return dataNascimento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_Cpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRB_Feminino = new javax.swing.JRadioButton();
        jRB_Masculino = new javax.swing.JRadioButton();
        jS_Dia = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jS_Mes = new javax.swing.JSpinner();
        jS_Ano = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jCB_Curso = new javax.swing.JComboBox<>();
        jB_Salvar = new javax.swing.JButton();
        jB_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Docente");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");

        jTF_Nome.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CPF:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Gênero:");

        jRB_Feminino.setText("Feminino");
        jRB_Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_FemininoActionPerformed(evt);
            }
        });

        jRB_Masculino.setText("Masculino");
        jRB_Masculino.setToolTipText("");

        jS_Dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Data Nasc:");

        jS_Mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jS_Ano.setModel(new javax.swing.SpinnerNumberModel(2005, 1950, 2023, 1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Formacao:");

        jCB_Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Curso", "TADS", "Direito", "Gastronomia", "Contabilidade", "Engenharia Civil", "Arquitetura" }));
        jCB_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_CursoActionPerformed(evt);
            }
        });

        jB_Salvar.setBackground(java.awt.SystemColor.activeCaption);
        jB_Salvar.setText("Salvar");
        jB_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalvarActionPerformed(evt);
            }
        });

        jB_Cancelar.setBackground(java.awt.SystemColor.controlHighlight);
        jB_Cancelar.setText("Cancelar");
        jB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jB_Cancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jB_Salvar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTF_Nome)
                                .addComponent(jTF_Cpf)
                                .addComponent(jTF_Email)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRB_Feminino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRB_Masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jS_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jS_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jS_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCB_Curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRB_Feminino)
                    .addComponent(jRB_Masculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jS_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCB_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Salvar)
                    .addComponent(jB_Cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalvarActionPerformed
        nome = jTF_Nome.getText();
        cpf = jTF_Cpf.getText();
        email = jTF_Email.getText();

        genero = jRB_Feminino.isSelected() ? "Feminino" : "Masculino";
        int dia = (int) jS_Dia.getValue();
        int mes = (int) jS_Mes.getValue();
        int ano = (int) jS_Ano.getValue();
        dataNascimento = LocalDate.of(ano, mes, dia);

        formacao = jCB_Curso.getSelectedItem().toString();
        System.out.println("nome: " + nome);
        System.out.println("CPF: " + cpf);
        System.out.println("email: " + email);
        System.out.println("genero: " + genero);
        System.out.println("data nascimento: " + dataNascimento);
        System.out.println("formacao: " + formacao);

        if (!editar) {
            controleDocente.adicionarDocente(nome, cpf, email, genero, formacao, dataNascimento);
        }else{
            controleDocente.editarDocente(nome, cpf, email, genero, formacao, dataNascimento);
        }
        controleDocente.getTelaListagem().setarDadosTabela();
        setVisible(false);
    }//GEN-LAST:event_jB_SalvarActionPerformed

    private void jB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jB_CancelarActionPerformed

    private void jCB_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_CursoActionPerformed

    private void jRB_FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_FemininoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cancelar;
    private javax.swing.JButton jB_Salvar;
    private javax.swing.JComboBox<String> jCB_Curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB_Feminino;
    private javax.swing.JRadioButton jRB_Masculino;
    private javax.swing.JSpinner jS_Ano;
    private javax.swing.JSpinner jS_Dia;
    private javax.swing.JSpinner jS_Mes;
    private javax.swing.JTextField jTF_Cpf;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_Nome;
    // End of variables declaration//GEN-END:variables
}
